FROM node:16.15-alpine3.14

RUN mkdir -p /opt/app
WORKDIR /opt/app

RUN adduser -S app

COPY package.json ./

COPY yarn.lock ./

RUN yarn install --frozen-lockfile

COPY . .

RUN chown -R app /opt/app

USER app

EXPOSE 3000
CMD ["npm", "start"]
