# docker-compose.yml

version: "3.9"
services:
  postgres:
    container_name: db-vcodes-test
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: db-vcodes-test
    expose:
     - 5432
    ports:
      - '5432:5432'
    volumes:
      - db:/var/lib/postgresql/data

  test-vccodes:
    container_name: api-vcodes-test
    build:
      context: .
    environment:
      DB_SCHEMA: db-vcodes-test
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_HOST: postgres
    depends_on:
      - postgres
    ports:
      - '5000:5000'

volumes:
  db: